//! The vendored snapshot of the upstream event surface.
//!
//! `xtask/baseline/events.json` is the only thing `drift-check` compares
//! against in its offline mode, which is what CI runs. It is written by
//! `drift-check --refresh` and reviewed by a human in the pull request that
//! bumps it — that review is the point where an upstream protocol change is
//! consciously accepted.

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::drift::upstream::{self, Upstream};

/// Bumped when the meaning of the file changes, so an old baseline is reported
/// rather than silently misread.
pub const FORMAT: u32 = 1;

pub const UPSTREAM_REPO: &str = "ag-ui-protocol/ag-ui";
pub const UPSTREAM_PATH: &str = "sdks/typescript/packages/core/src/events.ts";

const NOTE: &str = "Generated by `cargo run -p xtask -- drift-check --refresh`. \
                    Reviewed by a human, never hand-edited.";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Baseline {
    #[serde(rename = "$note")]
    pub note: String,
    pub format: u32,
    pub source: Source,
    /// Fields every event inherits from `BaseEventSchema`. Recorded for the
    /// reader's benefit; they are excluded from per-event comparison.
    pub base_event_fields: Vec<Field>,
    /// `EventType` values in upstream declaration order.
    pub event_types: Vec<String>,
    /// One entry per event type, same order.
    pub events: Vec<Event>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Source {
    pub repo: String,
    pub path: String,
    /// Upstream commit the snapshot was taken at.
    pub commit: String,
    /// Date of that commit (ISO 8601, UTC).
    pub commit_date: String,
    /// Date `--refresh` ran (ISO 8601, UTC).
    pub fetched_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Field {
    pub name: String,
    pub required: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    pub fields: Vec<Field>,
    /// Set when the Zod schema could not be read confidently. Fields are then
    /// not compared, and `drift-check` reports a warning instead of a failure.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unparsed: Option<String>,
}

impl Baseline {
    /// Builds a baseline from a freshly extracted upstream surface.
    pub fn from_upstream(up: &Upstream, source: Source) -> Self {
        Self {
            note: NOTE.to_string(),
            format: FORMAT,
            source,
            base_event_fields: up.base_fields.iter().map(field).collect(),
            event_types: up.event_types.clone(),
            events: up
                .events
                .iter()
                .map(|e| Event {
                    event_type: e.event_type.clone(),
                    schema: e.schema.clone(),
                    fields: e.fields.iter().map(field).collect(),
                    unparsed: e.unparsed.clone(),
                })
                .collect(),
        }
    }

    pub fn load(path: &Path) -> Result<Self, String> {
        let text = std::fs::read_to_string(path).map_err(|e| {
            format!(
                "cannot read the vendored baseline at {}: {e}\n\
                 Create it with: cargo run -p xtask -- drift-check --refresh",
                path.display()
            )
        })?;
        let baseline: Self = serde_json::from_str(&text)
            .map_err(|e| format!("{} is not a valid baseline: {e}", path.display()))?;
        if baseline.format != FORMAT {
            return Err(format!(
                "{} was written in format {} but this xtask reads format {FORMAT}.\n\
                 Re-capture it with: cargo run -p xtask -- drift-check --refresh",
                path.display(),
                baseline.format
            ));
        }
        Ok(baseline)
    }

    pub fn save(&self, path: &Path) -> Result<(), String> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
        }
        let mut json = serde_json::to_string_pretty(self)
            .map_err(|e| format!("cannot serialise the baseline: {e}"))?;
        json.push('\n');
        std::fs::write(path, json).map_err(|e| format!("{}: {e}", path.display()))
    }

    pub fn event(&self, event_type: &str) -> Option<&Event> {
        self.events.iter().find(|e| e.event_type == event_type)
    }
}

fn field(f: &upstream::Field) -> Field {
    Field {
        name: f.name.clone(),
        required: f.required,
    }
}
